### ISSUE TITLE
Improve style of dropdown menu

### ISSUE THREAD

**Issue by TheVirtualMachine** [mcpt/mcpt.github.io#17]
### Who are you

I am:
- [x] An official member of the MCPT website development process
- [ ] Just someone who wants to help

----------------------------------------

### Issue
https://github.com/mcpt/mcpt.github.io/issues/11#issuecomment-356144192
"Right now, the dropdown looks really ugly, maybe remove the lines, unround the corners, and add a shadow similar to the one in the header?
Also, personally I think it would look better if the text or background changed color, instead of underlining the text"

### Pages affected
- Navigation bar

**Comment by angela-wang1** [comment]
Was just about to comment in the previous issue but here: On the bright side, it works xD But ^^ I would also say unround the corners and get rid of the black lines. Instead of underlining for the sub menus, we can highlight the background with a lighter hue of blue. Also, in order to make the different pages "Home" "Members" "Learn" "Contact" stand out more from each other, if possible, underline the bottom with the same hue of blue used previously. http://sharemywrite.com/ <-- just a demo site but it contains the idea of the underlining I'm talking about (not underlining the text)
